[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.30"
evm_version = "cancun"
allow_internal_expect_revert = true
bytecode_hash = "none"
cbor_metadata = false
dynamic_test_linking = true
ffi = true
fs_permissions = [{ access = "read-write", path = "./" }]
optimizer = true
optimizer_runs = 44444444
via_ir = true
verbosity = 2

remappings = [
	"forge-std/=lib/forge-std/src/",
	"@openzeppelin/=lib/openzeppelin-contracts/contracts/"
]

[fmt]
line_length = 120
tab_width = 4
quote_style = "double"
func_attrs_with_params_multiline = true
inline_attribute_style = "compact"
return_statement = "inline"

[fuzz]
run = 5000

[lint]
lint_on_build = false

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
optimism = "${OPTIMISM_RPC_URL}"
optimism-sepolia = "${OPTIMISM_SEPOLIA_RPC_URL}"
bsc = "${BSC_RPC_URL}"
bsc-testnet = "${BSC_TESTNET_RPC_URL}"
unichain = "${UNICHAIN_RPC_URL}"
unichain-sepolia = "${UNICHAIN_SEPOLIA_RPC_URL}"
polygon = "${POLYGON_RPC_URL}"
polygon-amoy = "${AMOY_RPC_URL}"
base = "${BASE_RPC_URL}"
base-sepolia = "${BASE_SEPOLIA_RPC_URL}"
arbitrum = "${ARBITRUM_RPC_URL}"
arbitrum-sepolia = "${ARBITRUM_SEPOLIA_RPC_URL}"
avalanche = "${AVALANCHE_RPC_URL}"
avalanche-sepolia = "${FUJI_RPC_URL}"
linea = "${LINEA_RPC_URL}"
linea-sepolia = "${LINEA_SEPOLIA_RPC_URL}"
scroll = "${SCROLL_RPC_URL}"
scroll-sepolia = "${SCROLL_SEPOLIA_RPC_URL}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}", chainId = 1 }
sepolia = { key = "${ETHERSCAN_API_KEY}", chainId = 11155111 }
optimism = { key = "${ETHERSCAN_API_KEY}", chainId = 10 }
optimism-sepolia = { key = "${ETHERSCAN_API_KEY}", chainId = 11155420 }
bsc = { key = "${ETHERSCAN_API_KEY}", chainId = 56 }
bsc-testnet = { key = "${ETHERSCAN_API_KEY}", chainId = 97 }
unichain = { key = "${ETHERSCAN_API_KEY}", chainId = 130 }
unichain-sepolia = { key = "${ETHERSCAN_API_KEY}", chainId = 1301 }
polygon = { key = "${ETHERSCAN_API_KEY}", chainId = 137 }
polygon-amoy = { key = "${ETHERSCAN_API_KEY}", chainId = 80002 }
base = { key = "${ETHERSCAN_API_KEY}", chainId = 8453 }
base-sepolia = { key = "${ETHERSCAN_API_KEY}", chainId = 84532 }
arbitrum = { key = "${ETHERSCAN_API_KEY}", chainId = 42161 }
arbitrum-sepolia = { key = "${ETHERSCAN_API_KEY}", chainId = 421614 }
avalanche = { key = "${ETHERSCAN_API_KEY}", chainId = 43114 }
avalanche-fuji = { key = "${ETHERSCAN_API_KEY}", chainId = 43113 }
linea = { key = "${ETHERSCAN_API_KEY}", chainId = 59144 }
linea-sepolia = { key = "${ETHERSCAN_API_KEY}", chainId = 59141 }
scroll = { key = "${ETHERSCAN_API_KEY}", chainId = 534352 }
scroll-sepolia = { key = "${ETHERSCAN_API_KEY}", chainId = 534351 }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
