[mainnet]
endpoint_url = "${MAINNET_RPC_URL}"

[mainnet.address]
weth = "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
steth = "0xae7ab96520DE3A18E5e111B5EaAb095312D7fE84"
eeth = "0x35fA164735182de50811E8e2E824cFb9B6118ac2"
wbtc = "0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599"
dai = "0x6B175474E89094C44Da98b954EedeAC495271d0F"
usdc = "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"
usdt = "0xdAC17F958D2ee523a2206206994597C13D831ec7"

[optimism]
endpoint_url = "${OPTIMISM_RPC_URL}"

[optimism.address]
weth = "0x4200000000000000000000000000000000000006"
wbtc = "0x68f180fcCe6836688e9084f035309E29Bf0A2095"
dai = "0xDA10009cBd5D07dd0CeCc66161FC93D7c9000da1"
usdc = "0x7F5c764cBc14f9669B88837ca1490cCa17c31607"
usdt = "0x94b008aA00579c1307B0EF2c499aD98a8ce58e58"

[bsc]
endpoint_url = "${BSC_RPC_URL}"

[bsc.address]
weth = "0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c"
wbtc = "0x0555E30da8f98308EdB960aa94C0Db47230d2B9c"
dai = "0x1AF3F329e8BE154074D8769D1FFa4eE058B1DBc3"
usdc = "0x8AC76a51cc950d9822D68b83fE1Ad97B32Cd580d"
usdt = "0x55d398326f99059fF775485246999027B3197955"

[unichain]
endpoint_url = "${UNICHAIN_RPC_URL}"

[unichain.address]
weth = "0x4200000000000000000000000000000000000006"
wbtc = "0x0555E30da8f98308EdB960aa94C0Db47230d2B9c"
dai = "0x20CAb320A855b39F724131C69424240519573f81"
usdc = "0x078D782b760474a361dDA0AF3839290b0EF57AD6"
usdt = "0x9151434b16b9763660705744891fA906F660EcC5"

[polygon]
endpoint_url = "${POLYGON_RPC_URL}"

[polygon.address]
weth = "0x0d500B1d8E8eF31E21C99d1Db9A6444d3ADf1270"
wbtc = "0x1BFD67037B42Cf73acF2047067bd4F2C47D9BfD6"
dai = "0x8f3Cf7ad23Cd3CaDbD9735AFf958023239c6A063"
usdc = "0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174"
usdt = "0xc2132D05D31c914a87C6611C10748AEb04B58e8F"

[base]
endpoint_url = "${BASE_RPC_URL}"

[base.address]
weth = "0x4200000000000000000000000000000000000006"
wbtc = "0x0555E30da8f98308EdB960aa94C0Db47230d2B9c"
dai = "0x50c5725949A6F0c72E6C4a641F24049A917DB0Cb"
usdc = "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913"
usdt = "0xfde4C96c8593536E31F229EA8f37b2ADa2699bb2"

[arbitrum]
endpoint_url = "${ARBITRUM_RPC_URL}"

[arbitrum.address]
weth = "0x82aF49447D8a07e3bd95BD0d56f35241523fBab1"
wbtc = "0x2f2a2543B76A4166549F7aaB2e75Bef0aefC5B0f"
dai = "0xDA10009cBd5D07dd0CeCc66161FC93D7c9000da1"
usdc = "0xFF970A61A04b1cA14834A43f5dE4533eBDDB5CC8"
usdt = "0xFd086bC7CD5C481DCC9C85ebE478A1C0b69FCbb9"

[avalanche]
endpoint_url = "${AVALANCHE_RPC_URL}"

[avalanche.address]
weth = "0xB31f66AA3C1e785363F0875A1B74E27b85FD66c7"
wbtc = "0x50b7545627a5162F82A992c33b87aDc75187B218"
dai = "0xd586E7F844cEa2F87f50152665BCbc2C279D8d70"
usdc = "0xB97EF9Ef8734C71904D8002F8b6Bc66Dd9c48a6E"
usdt = "0x9702230A8Ea53601f5cD2dc00fDBc13d4dF4A8c7"

[linea]
endpoint_url = "${LINEA_RPC_URL}"

[linea.address]
weth = "0xe5D7C2a44FfDDf6b295A15c148167daaAf5Cf34f"
wbtc = "0x3aAB2285ddcDdaD8edf438C1bAB47e1a9D05a9b4"
dai = "0x4AF15ec2A0BD43Db75dd04E62FAA3B8EF36b00d5"
usdc = "0x176211869cA2b568f2A7D4EE941E073a821EE1ff"
usdt = "0xA219439258ca9da29E9Cc4cE5596924745e12B93"

[scroll]
endpoint_url = "${SCROLL_RPC_URL}"

[scroll.address]
weth = "0x5300000000000000000000000000000000000004"
wbtc = "0x3C1BCa5a656e69edCD0D4E36BEbb3FcDAcA60Cf1"
dai = "0xcA77eB3fEFe3725Dc33bccB54eDEFc3D9f764f97"
usdc = "0x06eFdBFf2a14a7c8E15944D1F4A48F9F95F663A4"
usdt = "0xf55BEC9cafDbE8730f096Aa55dad6D22d44099Df"
